name: Release Helm Chart (OCI)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify Chart Version matches Release Tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          CHART_VERSION=$(yq eval '.version' Chart.yaml | sed 's/^v//')
          TAG_VERSION=$(echo ${GITHUB_REF_NAME} | sed 's/^v//')
          if [ "$CHART_VERSION" != "$TAG_VERSION" ]; then
            echo "Error: Chart.yaml version (épurée: $CHART_VERSION) ne correspond pas au tag de release (épuré: $TAG_VERSION)"
            echo "Assurez-vous que la version dans Chart.yaml correspond au tag de release Git (ex: tag 'v1.2.3' -> Chart version '1.2.3')"
            exit 1
          fi
          echo "Success: Chart.yaml version ($CHART_VERSION) correspond au tag de release ($TAG_VERSION)"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Package Helm Chart
        run: |
          CHART_NAME=$(yq eval '.name' Chart.yaml)
          CHART_VERSION=$(yq eval '.version' Chart.yaml)
          helm package .

      - name: Push Helm Chart to GHCR
        run: |
          CHART_NAME=$(yq eval '.name' Chart.yaml)
          CHART_VERSION=$(yq eval '.version' Chart.yaml)
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          helm push ${CHART_NAME}-${CHART_VERSION}.tgz oci://ghcr.io/${REPO_OWNER}/charts

      - name: Setup ORAS
        uses: oras-project/setup-oras@v1

      - name: Tag and Push Helm Chart as latest to GHCR
        run: |
          CHART_NAME=$(yq eval '.name' Chart.yaml)
          CHART_VERSION=$(yq eval '.version' Chart.yaml)
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          
          # On s'assure d'être connecté au registre pour oras
          echo "${{ secrets.GITHUB_TOKEN }}" | oras login ghcr.io -u ${{ github.actor }} --password-stdin
          
          # ORAS n'utilise pas le préfixe 'oci://' (utilisé par Helm)
          SOURCE_IMAGE="ghcr.io/${REPO_OWNER}/charts/${CHART_NAME}:${CHART_VERSION}"
          TARGET_IMAGE="ghcr.io/${REPO_OWNER}/charts/${CHART_NAME}:latest"
          
          echo "Copying $SOURCE_IMAGE to $TARGET_IMAGE"
          oras cp $SOURCE_IMAGE $TARGET_IMAGE
